[Settings]
ID = "d2668848-c2a6-411f-b884-004faee1942f"
[build]
functions = "./.netlify/functions"
# Specify is-core-module/package.json as an external dependency
ignore = "is-core-module/package.json"