export enum HTMLItem {
  P = "p",
  H1 = "h1",
  H2 = "h2",
  H3 = "h3",
  H4 = "h4",
  H5 = "h5",
  H6 = "h6",
  UL = "ul",
  A = "a",
  IMG = "img",
  BLOCKQUOTE = "blockquote",
  CODE = "code",
  EM = "em",
  STRONG = "strong",
  DEL = "del",
  HTML = "html",
  SUP = "sup",
  LI = "li",
  TABLE = "table",
  TR = "tr",
  TD = "td",
  HR = "hr",
  BR = "br",
  DL = "dl",
  PRE = "pre",
}
