// All types supported by standard Markdown and GFM
export enum MarkdownItem {
  // Standard Markdown
  BlockQuote = "blockquote",
  Break = "break",
  Code = "code",
  Definition = "definition",
  Emphasis = "emphasis",
  Heading = "heading",
  Heading1 = "heading1",
  Heading2 = "heading2",
  Heading3 = "heading3",
  Heading4 = "heading4",
  Heading5 = "heading5",
  Heading6 = "heading6",
  HTML = "html",
  Image = "image",
  ImageReference = "imageReference",
  InlineCode = "inlineCode",
  Link = "link",
  LinkReference = "linkReference",
  List = "list",
  ListItem = "listItem",
  Paragraph = "paragraph",
  Root = "root",
  Strong = "strong",
  Text = "text",
  ThematicBreak = "thematicBreak",
  // GFM
  Delete = "delete",
  FootnoteDefinition = "footnoteDefinition",
  FootnoteReference = "footnoteReference",
  Table = "table",
  TableCell = "tableCell",
  TableRow = "tableRow",
}
export const MarkdownItems = [
  MarkdownItem.BlockQuote,
  MarkdownItem.Break,
  MarkdownItem.Code,
  MarkdownItem.Definition,
  MarkdownItem.Emphasis,
  MarkdownItem.Heading,
  MarkdownItem.HTML,
  MarkdownItem.Image,
  MarkdownItem.ImageReference,
  MarkdownItem.InlineCode,
  MarkdownItem.Link,
  MarkdownItem.LinkReference,
  MarkdownItem.List,
  MarkdownItem.ListItem,
  MarkdownItem.Paragraph,
  MarkdownItem.Root,
  MarkdownItem.Strong,
  MarkdownItem.Text,
  MarkdownItem.ThematicBreak,
  MarkdownItem.Delete,
  MarkdownItem.FootnoteDefinition,
  MarkdownItem.FootnoteReference,
  MarkdownItem.Table,
  MarkdownItem.TableCell,
  MarkdownItem.TableRow,
] as const;
