import { ISSUE_LABELS } from "./constants";

export const TimeLabelWeights: Record<string, number> = {
  [ISSUE_LABELS.TIME_LT_1DAY]: 1,
  [ISSUE_LABELS.TIME_LT_1WEEK]: 2,
  [ISSUE_LABELS.TIME_LT_2WEEKS]: 3,
  [ISSUE_LABELS.TIME_LT_1MONTH]: 4,
  [ISSUE_LABELS.TIME_GTE_1MONTH]: 5,
};

export const TimeTargetLabels: Record<string, string> = {
  [ISSUE_LABELS.TIME_LT_1DAY]: ISSUE_LABELS.PRICE_100_1000,
  [ISSUE_LABELS.TIME_LT_1WEEK]: ISSUE_LABELS.PRICE_200_2000,
  [ISSUE_LABELS.TIME_LT_2WEEKS]: ISSUE_LABELS.PRICE_300_3000,
  [ISSUE_LABELS.TIME_LT_1MONTH]: ISSUE_LABELS.PRICE_400_4000,
  [ISSUE_LABELS.TIME_GTE_1MONTH]: ISSUE_LABELS.PRICE_500_5000,
};

export const ProfitLabelWeights: Record<string, number> = {
  [ISSUE_LABELS.PROFIT_LT_10]: 1,
  [ISSUE_LABELS.PROFIT_LT_50]: 5,
  [ISSUE_LABELS.PROFIT_LT_100]: 10,
  [ISSUE_LABELS.PROFIT_GTE_100]: 20,
};

export const ProfitTargetLabels: Record<string, string> = {
  [ISSUE_LABELS.PROFIT_LT_10]: ISSUE_LABELS.PRICE_100_400,
  [ISSUE_LABELS.PROFIT_LT_50]: ISSUE_LABELS.PRICE_500_2000,
  [ISSUE_LABELS.PROFIT_LT_100]: ISSUE_LABELS.PRICE_1000_4000,
  [ISSUE_LABELS.PROFIT_GTE_100]: ISSUE_LABELS.PRICE_2000_8000,
};
