ALTER TABLE wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly DISABLE ROW LEVEL SECURITY;
ALTER TABLE access DISABLE ROW LEVEL SECURITY;
ALTER TABLE penalty DISABLE ROW LEVEL SECURITY;
ALTER TABLE multiplier DISABLE ROW LEVEL SECURITY;

CREATE POLICY "Anon users can update permits table" 
ON permits FOR update
TO anon
USING (true)