ALTER TABLE permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE access ENABLE ROW LEVEL SECURITY;
ALTER TABLE penalty ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for frontend" ON "public"."permits"
AS PERMISSIVE FOR SELECT
TO public
USING (true)