ALTER TABLE wallets
ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;

ALTER TABLE access
ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL,
ADD COLUMN IF NOT EXISTS repository_id bigint NOT NULL;

ALTER TABLE penalty
ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL,
ADD COLUMN IF NOT EXISTS repository_id bigint NOT NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
