name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install latest yarn version
        run: yarn set version latest

      - name: Install dependencies
        run: yarn install

      - name: Local Build
        run: yarn build
